### PR TITLE
Homepage

### PR DESCRIPTION
**Pull request by ttahm3d**
- created homepage
- added empty rules page
127 0 0 1_5500_index html (1)

### CODE REVIEW

**Review by nishasen — APPROVED** [review]
Good to merge , code looks clean.

**Review by krishanu2911 — APPROVED** [review]
Looks good to go !!!!!! no changes required

**Review by nakulsharma15 — APPROVED** [review]
Looks good to me. No changes suggested

**Review by Sameony — APPROVED** [review]
very descriptive commit messages and class name. Good work

**Pull request merged**
